### ISSUE TITLE
workload with reliability risks

### ISSUE THREAD

**Issue by aburhan** [aburhan/gke-opt-demo#31]
**Provisioning Assessment:**

Based on the provided workload structure, it appears that the workload is currently over-provisioned in terms of both CPU and memory resources.

- **CPU:** The workload's average CPU utilization is only around 1.9%, indicating that the allocated CPU resources are not being fully utilized. The recommended CPU request is 8 mCores, while the recommended CPU limit is 12 mCores. This suggests that the workload could potentially run effectively with a smaller CPU allocation.

- **Memory:** Similarly, the workload's maximum memory utilization is around 48% of the allocated memory. The recommended memory request is 109 MiB, while the recommended memory limit is also 109 MiB. This indicates that the workload could potentially run effectively with a smaller memory allocation.

**Compute Instance Recommendation:**

Given the workload's resource requirements and the image type ("nginx"), a suitable compute instance recommendation would be an **A2** instance type. The A2 instance type provides 2 vCPUs and 8 GiB of memory, which should be sufficient to accommodate the workload's resource needs.

**Note:** The specific compute instance recommendation may vary depending on the actual application requirements and workload characteristics. It is always advisable to conduct performance testing and monitoring to fine-tune the resource allocation and ensure optimal performance.

**Please update the container: main resources request **

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: loadgenerator
spec:
  selector:
    matchLabels:
      app: loadgenerator
  ...
      containers:
      - name: main
        resources:
          requests:
            cpu: 8m
            memory: 109Mi
          limits:
            cpu: 12m
            memory: 109Mi
```
